# Generated by Django 2.0.3 on 2018-03-07 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseID', models.CharField(max_length=10)),
                ('connCourseID', models.CharField(max_length=10)),
                ('overallNode', models.IntegerField()),
                ('difficultyNode', models.IntegerField()),
                ('cohesionNode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('courseID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('courseName', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Majors',
            fields=[
                ('majorCode', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('majorName', models.CharField(max_length=35)),
                ('majorCourses', models.CharField(max_length=500)),
                ('sideCourses', models.CharField(max_length=500)),
                ('electives', models.IntegerField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='courselinks',
            unique_together={('courseID', 'connCourseID')},
        ),
    ]
