# Generated by Django 2.0.3 on 2018-03-07 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleGen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courselinks',
            name='cohseionNodeWeight',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courselinks',
            name='difficultyNodeWeight',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courselinks',
            name='cohesionNode',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='courselinks',
            name='difficultyNode',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='courselinks',
            name='overallNode',
            field=models.FloatField(),
        ),
    ]
