# Generated by Django 2.0.3 on 2018-03-28 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleGen', '0002_auto_20180307_0537'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='creditHours',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
